### ISSUE TITLE
Can you tell me the reason for this error?

### ISSUE THREAD

**Issue by mengtun** [Nenkai/GBFRDataTools#3]
E:\mod\gbfrlink\GBFRDataTools.exe>E:\mod\gbfrlink\GBFRDataTools.exe\GBFRDataTools.exe extract-all -i "E:\SteamLibrary\steamapps\common\Granblue Fantasy Relink\data.0"
-----------------------------------------
- GBFRDataTools by Nenkai/WistfulHopes
-----------------------------------------
- https://github.com/Nenkai
- https://github.com/WistfulHopes
-----------------------------------------
Opening archive index 'E:\SteamLibrary\steamapps\common\Granblue Fantasy Relink\data.0'
Unhandled exception. System.IO.EndOfStreamException: Could not read 4 bytes.
   at Syroot.BinaryData.StreamExtensions.FillBuffer(Stream stream, Int32 length)
   at Syroot.BinaryData.StreamExtensions.ReadInt32(Stream stream, ByteConverter converter)
   at Syroot.BinaryData.StreamExtensions.ReadString(Stream stream, StringCoding coding, Encoding encoding, ByteConverter converter)
   at GBFRDataTools.Archive.IndexFile.ReadCodenameField(BinaryStream bs, UInt32 fieldOffset) in C:\Users\nenkai\source\repos\GRBFDataTools\GBFRDataTools\Archive\IndexFile.cs:line 220
   at GBFRDataTools.Archive.IndexFile.ReadInternal(BinaryStream bs) in C:\Users\nenkai\source\repos\GRBFDataTools\GBFRDataTools\Archive\IndexFile.cs:line 102
   at GBFRDataTools.Archive.IndexFile.Read(String fileName) in C:\Users\nenkai\source\repos\GRBFDataTools\GBFRDataTools\Archive\IndexFile.cs:line 65
   at GBFRDataTools.Archive.DataArchive.Init(String indexFile) in C:\Users\nenkai\source\repos\GRBFDataTools\GBFRDataTools\Archive\Archive.cs:line 37
   at GBFRDataTools.Program.ExtractAll(ExtractAllVerbs verbs) in C:\Users\nenkai\source\repos\GRBFDataTools\GBFRDataTools\Program.cs:line 61
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at GBFRDataTools.Program.Main(String[] args) in C:\Users\nenkai\source\repos\GRBFDataTools\GBFRDataTools\Program.cs:line 20

**Comment by Nenkai** [comment]
You must extract from the `data.i` file. Not the numbered files.

**Comment by mengtun** [comment]
> 您必须从文件中提取。不是编号的文件。`data.i`
I see, thanks for the reply

**Comment by mengtun** [comment]
> You must extract from the `data.i` file. Not the numbered files.

I see, thanks for the reply
